<Project Sdk="Microsoft.NET.Sdk">

<PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>

	<IsPackable>false</IsPackable>
	<IsTestProject>true</IsTestProject>

	<PreserveCompilationContext>true</PreserveCompilationContext>
	<GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="Respawn" Version="7.0.0" />
    <PackageReference Include="Testcontainers.PostgreSql" Version="4.15.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
	<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="API\Controllers\Admins\" />
    <Folder Include="Infrastructure\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.API\Ecommerce.API.csproj" />
    <ProjectReference Include="..\Ecommerce.Application\Ecommerce.Application.csproj" />
    <ProjectReference Include="..\Ecommerce.Domain\Ecommerce.Domain.csproj" />
    <ProjectReference Include="..\Ecommerce.Infrastructure\Ecommerce.Infrastructure.csproj" />
  </ItemGroup>

</Project>
